# Generated by Django 2.1.7 on 2019-02-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exchnges',
            new_name='Exchanges',
        ),
    ]
