# Generated by Django 2.1.7 on 2019-02-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190215_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='exchanges',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
