# Generated by Django 2.1.7 on 2019-02-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190215_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='exchange_price',
            field=models.IntegerField(default=''),
        ),
    ]
