# Generated by Django 2.1.7 on 2019-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_exchanges_exchange_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='exchange_price',
            field=models.IntegerField(default=0),
        ),
    ]
