# Generated by Django 2.1.7 on 2019-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190215_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='exchange_price',
            field=models.IntegerField(max_length=10),
        ),
    ]
