# Generated by Django 2.1.7 on 2019-02-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190215_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanges',
            old_name='exchange_price',
            new_name='price',
        ),
    ]
