# Generated by Django 2.1.7 on 2019-02-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190215_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
