# Generated by Django 2.1.7 on 2019-02-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190215_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchanges',
            name='price',
        ),
    ]
